#' Title rbioUtil_perm_plot
#'
#' @description Generic plotting function for permutation test results.
#' @param perm_res Permutation test results object. The object should be either \code{rbiosvm_perm}, or \code{rbiomvr_perm} classes.
#' @param ... Additional argument for the plot settings, see details.
#' @return A pdf file containing a scatter plot for permutation results.
#' @examples
#'
#' \dontrun{
#' rbioUtil_perm_plot(perm_res = svm_model_perm)
#' }
#'
#' @export
rbioUtil_perm_plot <- function(perm_res, ...){
  UseMethod("rbioUtil_perm_plot", perm_res)
}


#' Title rbioUtil_perm_plot.rbiosvm_perm
#'
#' @description Plotting function for SVM permutation test results.
#' @param perm_res Permutation test results object. The object should be \code{rbiosvm_perm} class.
#' @param plot.SymbolSize Symbol size. Default is \code{2}.
#' @param plot.Width Scoreplot width. Default is \code{170}.
#' @param plot.Height Scoreplot height. Default is \code{150}.
#' @param ... Additional argument for the plot settings.
#' @param verbose Wether to display messages. Default is \code{TRUE}. This will not affect error or warning messeages.
#' @return A pdf file containing a scatter plot for permutation results.
#' @method rbioUtil_perm_plot rbiosvm_perm
#' @export
rbioUtil_perm_plot.rbiosvm_perm <- function(perm_res, plot.SymbolSize = 2,
                                            plot.Width = 170, plot.Height = 150,
                                            ...,
                                            verbose = TRUE){
  # plot dfm
  perm_res_dfm <- perm_res$perm.results

  # plot
  baseplt <- ggplot(data = perm_res_dfm, aes(x = nperm, y = stats)) +
    geom_line(linetype = "dashed") +
    geom_point(size = plot.SymbolSize) +
    geom_hline(yintercept = perm_res_dfm[1, 2], linetype = "dashed", colour = "red")

  plt <- rbioUtil_perm_plot.default(baseplt = baseplt, plot.yLabel = "Accuracy", ...)

  # save
  if (verbose) cat(paste("Plot being saved to file: ", deparse(substitute(perm_res)),".svm.perm.plot.pdf...", sep = ""))  # initial message
  grid.newpage()
  ggsave(filename = paste(deparse(substitute(perm_res)),".svm.perm.plot.pdf", sep = ""), plot = plt,
         width = plot.Width, height = plot.Height, units = "mm",dpi = 600)
  grid.draw(plt)
  if(verbose) cat("Done! \n")
}


#' Title rbioUtil_perm_plot.rbiomvr_perm
#'
#' @description Plotting function for PLS-DA permutation test results.
#' @param perm_res Permutation test results object. The object should be \code{rbiomvr_perm} class.
#' @param plot.SymbolSize Symbol size. Default is \code{2}.
#' @param plot.Width Scoreplot width. Default is \code{170}.
#' @param plot.Height Scoreplot height. Default is \code{150}.
#' @param ... Additional argument for the plot settings.
#' @param verbose Wether to display messages. Default is \code{TRUE}. This will not affect error or warning messeages.
#' @return A pdf file containing a scatter plot for permutation results.
#' @method rbioUtil_perm_plot rbiomvr_perm
#' @export
rbioUtil_perm_plot.rbiomvr_perm <- function(perm_res, plot.SymbolSize = 2,
                                            plot.Width = 170, plot.Height = 150,
                                            ...,
                                            verbose = TRUE){
  # plot dfm
  perm_res_dfm <- perm_res$perm.results

  # plot
  baseplt <- ggplot(data = perm_res_dfm, aes(x = nperm, y = RMSEP, group = comparison)) +
    geom_line(aes(linetype = comparison, color = comparison)) +
    geom_point(aes(shape = comparison, color = comparison), size = plot.SymbolSize) +
    geom_hline(yintercept = perm_res_dfm[perm_res_dfm$nperm == 0, 3], linetype = "dashed", colour = "red")
  plt <- rbioUtil_perm_plot.default(baseplt = baseplt, plot.yLabel = "RMSEP", ...)

  # save
  if (verbose) cat(paste("Plot being saved to file: ", deparse(substitute(perm_res)),".plsda.perm.plot.pdf...", sep = ""))  # initial message
  grid.newpage()
  ggsave(filename = paste(deparse(substitute(perm_res)),".plsda.perm.plot.pdf", sep = ""), plot = plt,
         width = plot.Width, height = plot.Height, units = "mm",dpi = 600)
  grid.draw(plt)
  if(verbose) cat("Done! \n")
}


#' Title rbioUtil_perm_plot.default
#'
#' @description Core plotting function for SVM permutation test results.
#' @param baseplot A base plot generated by the \code{\link{rbioUtil_perm_plot}} method.
#' @param plot.display.Title If to show the name of the y class. Default is \code{TRUE}.
#' @param plot.titleSize The font size of the plot title. Default is \code{10}.
#' @param plot.fontType The type of font in the figure. Default is "sans". For all options please refer to R font table, which is avaiable on the website: \url{http://kenstoreylab.com/?page_id=2448}.
#' @param plot.xLabel X-axis label. Type with quotation marks. Could be NULL. Default is \code{"1 - specificity"}.
#' @param plot.xLabelSize X-axis label size. Default is \code{10}.
#' @param plot.xTickLblSize X-axis tick label size. Default is \code{10}.
#' @param plot.yLabel Y-axis label. Type with quotation marks. Could be NULL. Default is \code{"sensitivity"}.
#' @param plot.yLabelSize Y-axis label size. Default is \code{10}.
#' @param plot.yTickLblSize Y-axis tick label size. Default is \code{10}.
#' @param plot.legendSize Legend size. Default is \code{9}.
#' @param plot.rightsideY If to show the right side y-axis. Default is \code{FALSE}.
#' @return A baseplot object for permutation results.
#' @import ggplot2
#' @importFrom GGally ggpairs
#' @importFrom grid grid.newpage grid.draw
#' @importFrom RBioplot rightside_y multi_plot_shared_legend
#' @export
rbioUtil_perm_plot.default <- function(baseplt,
                                       plot.display.Title = TRUE, plot.titleSize = 10,
                                       plot.fontType = "sans",
                                       plot.xLabel = "Permutations", plot.xLabelSize = 10, plot.xTickLblSize = 10,
                                       plot.yLabel = "Accuracy", plot.yLabelSize = 10, plot.yTickLblSize = 10,
                                       plot.legendSize = 9,
                                       plot.rightsideY = TRUE){
  ## plot
  plt <- baseplt +
    ggtitle(ifelse(plot.display.Title, "Permutation test", NULL)) +
    xlab(plot.xLabel) +
    ylab(plot.yLabel) +
    theme(panel.background = element_rect(fill = 'white', colour = 'black'),
          panel.border = element_rect(colour = "black", fill = NA, size = 0.5),
          plot.title = element_text(face = "bold", size = plot.titleSize, family = plot.fontType, hjust = 0.5),
          axis.title.x = element_text(face = "bold", size = plot.xLabelSize, family = plot.fontType),
          axis.title.y = element_text(face = "bold", size = plot.yLabelSize, family = plot.fontType),
          legend.position = "bottom", legend.title = element_blank(), legend.text = element_text(size = plot.legendSize),
          legend.key = element_blank(),
          axis.text.x = element_text(size = plot.xTickLblSize, family = plot.fontType),
          axis.text.y = element_text(size = plot.yTickLblSize, family = plot.fontType, hjust = 0.5))

  if (plot.rightsideY){
    plt <- RBioplot::rightside_y(plt)
  }
  plt
}
